FROM centos:7
MAINTAINER "Preet" <preet050296@gmail.com>

RUN yum update -y
ADD ./rhcert /root/rhcert
WORKDIR /root/rhcert

RUN yum install -y wget
RUN wget http://debuginfo.centos.org/7/x86_64/kernel-debuginfo-3.10.0-514.el7.x86_64.rpm
RUN wget http://debuginfo.centos.org/7/x86_64/kernel-debuginfo-common-x86_64-3.10.0-514.el7.x86_64.rpm
RUN yum install kernel-debuginfo-common-x86_64-3.10.0-514.el7.x86_64.rpm kernel-debuginfo-3.10.0-514.el7.x86_64.rpm
 
RUN yum install -y *.rpm

